name: build-publish
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '*'
jobs:
  Android:
    runs-on: [ self-hosted, linux, x64 ]
    env:
      ANDROID_LOCATION: build/android/build-android-${{ github.sha }}.apk
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install dependencies
        run: npm ci

      - name: Build Android
        run: eas build -p android --profile=preview --local --non-interactive --output=${{env.ANDROID_LOCATION}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: android
          path: ${{env.ANDROID_LOCATION}}

  Publish:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: [ self-hosted, linux, x64 ]
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Publish app
        run: expo publish --release-channel=pr-${{ github.event.number }} --non-interactive

      - name: Save Expo Metadata
        uses: expo/expo-github-action/preview-comment@v7
        id: preview
        with:
          comment: false
          channel: pr-${{ github.event.number }}

      - name: Comment on PR
        uses: actions-cool/maintain-one-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ## Expo Build report for Pull Request #${{ github.event.number }}
            This App was automatically deployed for project **${{ steps.preview.outputs.projectName }}** on channel **pr-${{ github.event.number }}**.
            ### Current Build :rocket:
            - Built `.apk` for Android [here](https://github.com/ProgPrak-Native-App/react-native-app/actions/runs/${{ github.run_id }})
            - Expo link [here](${{ steps.preview.outputs.projectLink }})
            <img src="${{ steps.preview.outputs.projectQR }}" width="200" height="200">
