name: "Build Android APK"

on:
  workflow_dispatch: { }
  workflow_call:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm
          expo-cache: false
          eas-cache: false

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Get current package version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6

      - run: echo OUTPUT_LOCATION=build/android/KopfsachenRNA-${{ steps.extract_version.outputs.version }}.apk | tee "$GITHUB_ENV"

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm test:ci

      - name: Build Android
        run: eas build -p android --profile=preview --local --non-interactive --output=${{env.OUTPUT_LOCATION}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: android
          path: ${{ env.OUTPUT_LOCATION }}
