name: build-android

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch: { }

jobs:
  Android:
    runs-on: ubuntu-latest
    env:
      ANDROID_LOCATION: build/android/build-android-${{ github.sha }}.apk
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          #cache: npm

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm
          expo-cache: false
          eas-cache: false

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install dependencies
        run: npm ci

      - name: Build Android
        run: eas build -p android --profile=preview --local --non-interactive --output=${{env.ANDROID_LOCATION}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: android
          path: ${{env.ANDROID_LOCATION}}
