name: app_build
on: [pull_request]
# on every PR for now

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: expo publish --release-channel=pr-${{ github.event.number }} --non-interactive

      - name: Expo save Metadata
        uses: expo/expo-github-action/preview-comment@v7
        id: preview
        with:
          comment: false
          channel: pr-${{ github.event.number }}

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## Expo Build report for Pull Request #${{ github.event.number }} \n This pull request was automatically deployed for project **${{ steps.preview.outputs.projectSlug }}** on channel **pr-${{ github.event.number }}** . \n ### Project Info: \n - Name: **${{ steps.preview.outputs.projectName }}** \n - Link: ${{ steps.preview.outputs.projectLink }} \n <img src="${{ steps.preview.outputs.projectQR }}" width="200" height="200"> \n \n ### Build .apk/.ipa \n To build the app in Expo for internal distribution install expo-cli  by running `npm install -g expo-cli`. In order to build the app you will need an Expo account and the run `expo build:android -t apk` in the root folder.'})
