name: app_build
#on: [pull_request] change before merge!
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APK_LOCATION: android_build/kopfsachen-${{ github.ref_name }}-${{ github.event.number }}.apk
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: eas build -p android --profile=preview --local --non-interactive --output=${{env.APK_LOCATION}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: android-build
          path: ${{env.APK_LOCATION}}
