name: "Lint"

on:
  workflow_call: { }
  workflow_dispatch: { }

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: npm ci

      - name: Run ESLint
        run: npm run -- lint --output-file eslint_report.json --format json

      - name: Annotate Code Linting Results
        if: always()
        uses: ataylorme/eslint-annotate-action@1.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          report-json: eslint_report.json
