name: "Publish on expo.dev"

on:
  workflow_dispatch:
  workflow_call:

env:
  EXPO_PROJECT_ID: 2ed357a3-8d38-431d-bfaa-a6ed64e89caf

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm

      - name: Install dependencies
        run: npm ci

      - name: Publish EAS update
        run: |
          # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          echo 'EAS_UPDATE_RESULT<<EOF' >> $GITHUB_ENV
          # --auto sets the EAS branch name to the current git branch name and the update message to the HEAD commit message
          # --json causes information about the update to be sent to stdout and regular output to stderr
          # we redirect the json to an environment variable and the regular output back to stdout
          eas update --auto --json 2>&1 1>>$GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Generate summary
        env:
          RUNTIME_VERSION: ${{ fromJson(env.EAS_UPDATE_RESULT)[0].runtimeVersion }}
          UPDATE_GROUP_ID: ${{ fromJson(env.EAS_UPDATE_RESULT)[0].group }}
          DETAILS_URL: https://expo.dev/accounts/progprak_kopfsachen/projects/kopfsachen/updates/${{ env.UPDATE_GROUP_ID }}
          QR_URL: ${{ format('https://qr.expo.dev/eas-update?projectId={0}&channel={1}&runtimeVersion={2}&appScheme=exp', env.EXPO_PROJECT_ID, env.RUNTIME_VERSION, env.EAS_BRANCH) }}
        run: |
          EAS_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          
          echo 'REPORT<<EOF' >> $GITHUB_ENV
          # Write the report to the environment variable $REPORT and to the job summary at the same time
          cat <<EOF | tee -a $GITHUB_ENV $GITHUB_STEP_SUMMARY
          ## EAS Update Report for Pull Request #${{ github.event.number }}
          
          This app was automatically published on branch **$EAS_BRANCH**.
          View the update details [here]($DETAILS_URL).
          
          <img alt="Expo Go QR Code" src="$QR_URL" width="200" height="200">
          
          <!-- created by publish workflow -->
          EOF
          echo 'EOF' >> $GITHUB_ENV

      - name: Comment on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions-cool/maintain-one-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ env.REPORT }}
          body-include: <!-- created by publish workflow -->
