name: "Finish a release"

concurrency: release

on: workflow_dispatch

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          if [[ "$GITHUB_REF" != refs/heads/release/* ]]; then
            echo "::error title=Not a release branch::Refusing to merge non-release ref $GITHUB_REF into main"
            exit 1
          fi

  merge-into-main:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup git name
        run: |
          git config --local user.name "kopfsachen-rna-bot"
          git config --local user.email "<>"

      - name: Merge into main
        run: git pull --no-ff origin ${GITHUB_REF#refs/heads/}

      - name: Push
        run: git push

  merge-into-develop:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup git name
        run: |
          git config --local user.name "kopfsachen-rna-bot"
          git config --local user.email "<>"

      - name: Merge into main
        run: git pull --no-ff origin ${GITHUB_REF#refs/heads/}

      - name: Push
        run: git push

  delete-release-branch:
    needs: [merge-into-main, merge-into-develop]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Delete release branch
        run: git push origin --delete "${GITHUB_REF#refs/heads/}"
